- platform: integration
  source: sensor.dormitorio_aire_acondicionado_0200009211c7_wac_demand_response_power
  name: Energia AC kWh
  round: 3
  method: trapezoidal
  max_sub_interval:
    minutes: 1
